apiVersion: apps/v1
kind: Deployment
#datos como valores clave valor para identificar deployment
metadata:
  labels:
    app: ms-cursos
  #nombre de deployment
  name: ms-cursos
#se detalla la especificacion del deployment
spec:
  #especifica la cantidad de instancias que tendrá el pod
  replicas: 1
  selector:
    #indica que pod con label especifico va estar asociado
    matchLabels:
      #este valor debe ser igual a template.metadata.labels.app para enlazar pod a deployment
      app: ms-cursos
  #Detalle de configuracion de pod
  template:
    metadata:
      labels:
        app: ms-cursos
    #especificacion del pod asociado a deployment
    spec:
      #es una lista donde se especifica los contenedores e images a usar
      containers:
      #identificador de imagen
      - image: mpobletemori/ms-cursos:v1
        #nombre del pod a crear
        name: ms-cursos
        #detallar puertos a especificar
        ports:
        #puerto interno del pod
        - containerPort: 8002
        env:
        - name: PORT
          #seteo de variable en deployment
          #value: "8002"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-cursos
              key: port

        - name: DB_HOST
          #seteo de variable en deployment
          #value: "postgres14:5432"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-cursos
              key: db_host

        - name: DB_DATABASE
          #seteo de variable en deployment
          #value: "ms_cursos"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-cursos
              key: db_database

        - name: DB_USERNAME
          #seteo de variable en deployment
          #value: "postgres"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-cursos
              key: db_username

        - name: DB_PASSWORD
          #seteo de variable en deployment
          #value: "postgres"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-cursos
              key: db_password

        - name: USUARIOS_URL
          #seteo de variable en deployment
          #value: "ms-usuarios:8001"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-cursos
              key: usuarios_url

        imagePullPolicy: Always