apiVersion: apps/v1
kind: Deployment
#datos como valores clave valor para identificar deployment
metadata:
  labels:
    app: ms-usuarios
  #nombre de deployment
  name: ms-usuarios
#se detalla la especificacion del deployment
spec:
  #especifica la cantidad de instancias que tendrá el pod
  replicas: 4
  selector:
    #indica que pod con label especifico va estar asociado
    matchLabels:
      #este valor debe ser igual a template.metadata.labels.app para enlazar pod a deployment
      app: ms-usuarios
  #Detalle de configuracion de pod
  template:
    metadata:
      labels:
        app: ms-usuarios
    #especificacion del pod asociado a deployment
    spec:
      #es una lista donde se especifica los contenedores e images a usar
      containers:
      #identificador de imagen
      - image: mpobletemori/ms-usuarios:v1.3
        #nombre del pod a crear
        name: ms-usuarios
        #detallar puertos a especificar
        ports:
        #puerto interno del pod
        - containerPort: 8001
        env:
        #Inicio Variables de entorno de mismo kubernete
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #Fin Variables de entorno de mismo kubernete
        - name: PORT
          #seteo de variable en deployment
          #value: "8001"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-usuarios
              key: port

        - name: DB_HOST
          #seteo de variable en deployment
          #value: "mysql:3307"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-usuarios
              key: db_host

        - name: DB_DATABASE
          #seteo de variable en deployment
          #value: "ms_usuarios"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-usuarios
              key: db_database

        - name: DB_USERNAME
          #seteo de variable en deployment
          #value: "root"

          valueFrom:
            #seteo de variables desde configmap
            #configMapKeyRef:
              #name: configmap-ms-usuarios
              #key: db_username

            #seteo de variables desde secret
            secretKeyRef:
              name: secret-ms-usuarios
              key: db_username

        - name: DB_PASSWORD
          #seteo de variable en deployment
          #value: "sasa"

          valueFrom:
            #seteo de variables desde configmap
            #configMapKeyRef:
              #name: configmap-ms-usuarios
              #key: db_password

            #seteo de variables desde secret
            secretKeyRef:
               name: secret-ms-usuarios
               key: db_password

        - name: CURSOS_URL
          #seteo de variable en deployment
          #value: "ms-cursos:8002"

          #seteo de variables desde configmap
          valueFrom:
            configMapKeyRef:
              name: configmap-ms-usuarios
              key: cursos_url

        imagePullPolicy: Always