FROM openjdk:17-jdk-alpine as BUILDER

WORKDIR /app/ms-usuarios

COPY ./pom.xml /app
COPY ./ms-usuarios/.mvn ./.mvn
COPY ./ms-usuarios/mvnw .
COPY ./ms-usuarios/pom.xml .

RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/
#RUN ./mvnw dependency:go-offline

COPY ./ms-usuarios/src ./src

RUN ./mvnw clean package -DskipTests

FROM openjdk:17-jdk-alpine

WORKDIR /app
RUN mkdir ./logs
COPY --from=BUILDER /app/ms-usuarios/target/ms-usuarios-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8001

#Ejecuta comando inmutables
#ENTRYPOINT ["java","-jar","app.jar"]
#Ejecuta comando mutables para ejecutar modo interactivo en contenedores
CMD ["java","-jar","app.jar"]