ARG MS_NAME=ms-usuarios
FROM openjdk:17-jdk-alpine as BUILDER
ARG MS_NAME

WORKDIR /app/$MS_NAME

COPY ./pom.xml /app
COPY ./$MS_NAME/.mvn ./.mvn
COPY ./$MS_NAME/mvnw .
COPY ./$MS_NAME/pom.xml .

RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target/
#RUN ./mvnw dependency:go-offline

COPY ./$MS_NAME/src ./src

RUN ./mvnw clean package -DskipTests

FROM openjdk:17-jdk-alpine
ARG MS_NAME

WORKDIR /app
RUN mkdir ./logs

ARG TARGET_FOLDER=/app/$MS_NAME/target
ARG JAR_NAME=ms-usuarios-0.0.1-SNAPSHOT.jar
COPY --from=BUILDER $TARGET_FOLDER/$JAR_NAME ./app.jar

ARG PORT_APP=8001
#Variable de entorno
#puerto de aplicacion
ENV PORT $PORT_APP
EXPOSE $PORT

#Ejecuta comando inmutables
#ENTRYPOINT ["java","-jar","app.jar"]
#Ejecuta comando mutables para ejecutar modo interactivo en contenedores
CMD ["java","-jar","app.jar"]