apiVersion: v1
kind: Secret
metadata: 
  name: secret-ms-usuarios
type: Opaque
data:
  db_username: cm9vdA==
  db_password: c2FzYQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-ms-cursos
type: Opaque
data:
  db_username: cG9zdGdyZXM=
  db_password: cG9zdGdyZXM=
