apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3307
    protocol: TCP
    #puerto del deployment
    targetPort: 3307
  selector:
    #selector de pod que estara enganchado al service
    app: mysql
  type: ClusterIP