apiVersion: v1
kind: Service
metadata:
  name: ms-usuarios
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    #selector de pod que estara enganchado al service
    app: ms-usuarios
  type: LoadBalancer