apiVersion: v1
kind: Service
metadata:
  name: postgres14
spec:
  ports:
  - port: 5432
    protocol: TCP
    #puerto del deployment
    targetPort: 5432
  selector:
    #selector de pod que estara enganchado al service
    app: postgres14
  type: ClusterIP