server:
  port: 8090

spring:
  application:
    name: ms-apigateway

  cloud:
    gateway:
      routes:
        - id: ms-cursos
          uri: lb://ms-cursos
          predicates:
            - Path=/api/cursos/**
          filters:
            - StripPrefix=2

        - id: ms-usuarios
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2

