version: "3.4"

services:  
  mysql_db1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ms_usuarios'
      MYSQL_USER: 'mysql_user1'
      MYSQL_PASSWORD: 'sasa'
      MYSQL_ROOT_PASSWORD: 'sasa'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - mysql_db1_data:/var/lib/mysql
  postgres_db1:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes: 
      - postgres_db1_data:/var/lib/postgresql/data
volumes:
  mysql_db1_data:
    driver: local
  postgres_db1_data:
    driver: local
networks:
  default:
    name: mysql_db1_network
