version: "3.4"

services:  
  mysql_db1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ms_usuarios'
      MYSQL_USER: 'mysql_user1'
      MYSQL_PASSWORD: 'sasa'
      MYSQL_ROOT_PASSWORD: 'sasa'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    expose:
      - '3307'
    volumes:
      - mysql_db1_data:/var/lib/mysql  
volumes:  
  mysql_db1_data:
    driver: local  
networks:
  default:
    name: mysql_db1_network
