spring:
  application:
    name: ms-usuarios
  datasource:
    #En caso la DB este desplegada en red de docker
    # cambiar "host.docker.internal" por "nombre_contenedor bd"
    #url: jdbc:mysql://mysql8:3307/ms_usuarios
    url: jdbc:mysql://${DB_HOST:mysql:3307}/${DB_DATABASE:ms_usuarios}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class.name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  cloud:
    kubernetes:
      secrets:
        #Habilitar uso de secrets en kubernetes
        enable-api: true
      discovery:
        #realizar autodescubrimiento para todos los namespace en kubernete (por defecto lo realiza en man
        all-namespaces: true

  profiles:
    active: ${APP_SPRING_PROFILES_ACTIVE:dev}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
      client:
        registration:
          ms-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8001/authorized
            scope: read
            client-name: ms-usuarios-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000

server:
  port: ${PORT:8001}

logging:
  level:
    org.hibernate.SQL: debug
  file:
    path: /app/logs

ms-cursos:
  url: ${CURSOS_URL:ms-cursos:8002}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true