spring:
  application:
    name: ms-cursos
  datasource:
    #url: jdbc:postgresql://localhost:5432/ms_cursos
    #En caso la DB este desplegada en red de docker
    # cambiar "host.docker.internal" por "nombre_contenedor bd"
    #url: jdbc:postgresql://postgre14:5432/ms_cursos
    url: jdbc:postgresql://${DB_HOST:postgres14:5432}/${DB_DATABASE:ms_cursos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    kubernetes:
      secrets:
        #Habilitar uso de secrets en kubernetes
        enable-api: true
      discovery:
        #realizar autodescubrimiento para todos los namespace en kubernete (por defecto lo realiza en man
        all-namespaces: true

logging:
  level:
    org.hibernate.SQL: debug
  file:
    path: /app/logs

server:
  port: ${PORT:8002}

ms-usuarios:
    url: ${USUARIOS_URL:ms-usuarios:8001}
